// <auto-generated />
using System;
using BusinessObject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObject.Migrations
{
    [DbContext(typeof(CinemaContext))]
    partial class CinemaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BusinessObject.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContentBill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateBooking")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPay")
                        .HasColumnType("bit");

                    b.Property<string>("SeatBooking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ShowId")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("BookingId");

                    b.HasIndex("ShowId");

                    b.HasIndex("UserId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("BusinessObject.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryCode");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            CountryCode = "AF",
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            CountryCode = "AX",
                            CountryName = "Åland Islands"
                        },
                        new
                        {
                            CountryCode = "AL",
                            CountryName = "Albania"
                        },
                        new
                        {
                            CountryCode = "DZ",
                            CountryName = "Algeria"
                        },
                        new
                        {
                            CountryCode = "AS",
                            CountryName = "American Samoa"
                        },
                        new
                        {
                            CountryCode = "AD",
                            CountryName = "AndorrA"
                        },
                        new
                        {
                            CountryCode = "AO",
                            CountryName = "Angola"
                        },
                        new
                        {
                            CountryCode = "AI",
                            CountryName = "Anguilla"
                        },
                        new
                        {
                            CountryCode = "AQ",
                            CountryName = "Antarctica"
                        },
                        new
                        {
                            CountryCode = "AG",
                            CountryName = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryCode = "AR",
                            CountryName = "Argentina"
                        },
                        new
                        {
                            CountryCode = "AM",
                            CountryName = "Armenia"
                        },
                        new
                        {
                            CountryCode = "AW",
                            CountryName = "Aruba"
                        },
                        new
                        {
                            CountryCode = "AU",
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryCode = "AT",
                            CountryName = "Austria"
                        },
                        new
                        {
                            CountryCode = "AZ",
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            CountryCode = "BS",
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            CountryCode = "BH",
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            CountryCode = "BD",
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryCode = "BB",
                            CountryName = "Barbados"
                        },
                        new
                        {
                            CountryCode = "BY",
                            CountryName = "Belarus"
                        },
                        new
                        {
                            CountryCode = "BE",
                            CountryName = "Belgium"
                        },
                        new
                        {
                            CountryCode = "BZ",
                            CountryName = "Belize"
                        },
                        new
                        {
                            CountryCode = "BJ",
                            CountryName = "Benin"
                        },
                        new
                        {
                            CountryCode = "BM",
                            CountryName = "Bermuda"
                        },
                        new
                        {
                            CountryCode = "BT",
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            CountryCode = "BO",
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            CountryCode = "BA",
                            CountryName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryCode = "BW",
                            CountryName = "Botswana"
                        },
                        new
                        {
                            CountryCode = "BV",
                            CountryName = "Bouvet Island"
                        },
                        new
                        {
                            CountryCode = "BR",
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryCode = "IO",
                            CountryName = "British Indian Ocean Territory"
                        },
                        new
                        {
                            CountryCode = "BN",
                            CountryName = "Brunei Darussalam"
                        },
                        new
                        {
                            CountryCode = "BG",
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            CountryCode = "BF",
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            CountryCode = "BI",
                            CountryName = "Burundi"
                        },
                        new
                        {
                            CountryCode = "KH",
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            CountryCode = "CM",
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            CountryCode = "CA",
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryCode = "CV",
                            CountryName = "Cape Verde"
                        },
                        new
                        {
                            CountryCode = "KY",
                            CountryName = "Cayman Islands"
                        },
                        new
                        {
                            CountryCode = "CF",
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            CountryCode = "TD",
                            CountryName = "Chad"
                        },
                        new
                        {
                            CountryCode = "CL",
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryCode = "CN",
                            CountryName = "China"
                        },
                        new
                        {
                            CountryCode = "CX",
                            CountryName = "Christmas Island"
                        },
                        new
                        {
                            CountryCode = "CC",
                            CountryName = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            CountryCode = "CO",
                            CountryName = "Colombia"
                        },
                        new
                        {
                            CountryCode = "KM",
                            CountryName = "Comoros"
                        },
                        new
                        {
                            CountryCode = "CG",
                            CountryName = "Congo"
                        },
                        new
                        {
                            CountryCode = "CD",
                            CountryName = "Congo, The Democratic Republic of the"
                        },
                        new
                        {
                            CountryCode = "CK",
                            CountryName = "Cook Islands"
                        },
                        new
                        {
                            CountryCode = "CR",
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            CountryCode = "CI",
                            CountryName = "Cote D\"Ivoire"
                        },
                        new
                        {
                            CountryCode = "HR",
                            CountryName = "Croatia"
                        },
                        new
                        {
                            CountryCode = "CU",
                            CountryName = "Cuba"
                        },
                        new
                        {
                            CountryCode = "CY",
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            CountryCode = "CZ",
                            CountryName = "Czech Republic"
                        },
                        new
                        {
                            CountryCode = "DK",
                            CountryName = "Denmark"
                        },
                        new
                        {
                            CountryCode = "DJ",
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            CountryCode = "DM",
                            CountryName = "Dominica"
                        },
                        new
                        {
                            CountryCode = "DO",
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            CountryCode = "EC",
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            CountryCode = "EG",
                            CountryName = "Egypt"
                        },
                        new
                        {
                            CountryCode = "SV",
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            CountryCode = "GQ",
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryCode = "ER",
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            CountryCode = "EE",
                            CountryName = "Estonia"
                        },
                        new
                        {
                            CountryCode = "ET",
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            CountryCode = "FK",
                            CountryName = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            CountryCode = "FO",
                            CountryName = "Faroe Islands"
                        },
                        new
                        {
                            CountryCode = "FJ",
                            CountryName = "Fiji"
                        },
                        new
                        {
                            CountryCode = "FI",
                            CountryName = "Finland"
                        },
                        new
                        {
                            CountryCode = "FR",
                            CountryName = "France"
                        },
                        new
                        {
                            CountryCode = "GF",
                            CountryName = "French Guiana"
                        },
                        new
                        {
                            CountryCode = "PF",
                            CountryName = "French Polynesia"
                        },
                        new
                        {
                            CountryCode = "TF",
                            CountryName = "French Southern Territories"
                        },
                        new
                        {
                            CountryCode = "GA",
                            CountryName = "Gabon"
                        },
                        new
                        {
                            CountryCode = "GM",
                            CountryName = "Gambia"
                        },
                        new
                        {
                            CountryCode = "GE",
                            CountryName = "Georgia"
                        },
                        new
                        {
                            CountryCode = "DE",
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryCode = "GH",
                            CountryName = "Ghana"
                        },
                        new
                        {
                            CountryCode = "GI",
                            CountryName = "Gibraltar"
                        },
                        new
                        {
                            CountryCode = "GR",
                            CountryName = "Greece"
                        },
                        new
                        {
                            CountryCode = "GL",
                            CountryName = "Greenland"
                        },
                        new
                        {
                            CountryCode = "GD",
                            CountryName = "Grenada"
                        },
                        new
                        {
                            CountryCode = "GP",
                            CountryName = "Guadeloupe"
                        },
                        new
                        {
                            CountryCode = "GU",
                            CountryName = "Guam"
                        },
                        new
                        {
                            CountryCode = "GT",
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            CountryCode = "GG",
                            CountryName = "Guernsey"
                        },
                        new
                        {
                            CountryCode = "GN",
                            CountryName = "Guinea"
                        },
                        new
                        {
                            CountryCode = "GW",
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryCode = "GY",
                            CountryName = "Guyana"
                        },
                        new
                        {
                            CountryCode = "HT",
                            CountryName = "Haiti"
                        },
                        new
                        {
                            CountryCode = "HM",
                            CountryName = "Heard Island and Mcdonald Islands"
                        },
                        new
                        {
                            CountryCode = "VA",
                            CountryName = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            CountryCode = "HN",
                            CountryName = "Honduras"
                        },
                        new
                        {
                            CountryCode = "HK",
                            CountryName = "Hong Kong"
                        },
                        new
                        {
                            CountryCode = "HU",
                            CountryName = "Hungary"
                        },
                        new
                        {
                            CountryCode = "IS",
                            CountryName = "Iceland"
                        },
                        new
                        {
                            CountryCode = "IN",
                            CountryName = "India"
                        },
                        new
                        {
                            CountryCode = "ID",
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            CountryCode = "IR",
                            CountryName = "Iran, Islamic Republic Of"
                        },
                        new
                        {
                            CountryCode = "IQ",
                            CountryName = "Iraq"
                        },
                        new
                        {
                            CountryCode = "IE",
                            CountryName = "Ireland"
                        },
                        new
                        {
                            CountryCode = "IM",
                            CountryName = "Isle of Man"
                        },
                        new
                        {
                            CountryCode = "IL",
                            CountryName = "Israel"
                        },
                        new
                        {
                            CountryCode = "IT",
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryCode = "JM",
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            CountryCode = "JP",
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryCode = "JE",
                            CountryName = "Jersey"
                        },
                        new
                        {
                            CountryCode = "JO",
                            CountryName = "Jordan"
                        },
                        new
                        {
                            CountryCode = "KZ",
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            CountryCode = "KE",
                            CountryName = "Kenya"
                        },
                        new
                        {
                            CountryCode = "KI",
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            CountryCode = "KP",
                            CountryName = "Korea, Democratic People\"S Republic of"
                        },
                        new
                        {
                            CountryCode = "KR",
                            CountryName = "Korea, Republic of"
                        },
                        new
                        {
                            CountryCode = "KW",
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            CountryCode = "KG",
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryCode = "LA",
                            CountryName = "Lao People\"S Democratic Republic"
                        },
                        new
                        {
                            CountryCode = "LV",
                            CountryName = "Latvia"
                        },
                        new
                        {
                            CountryCode = "LB",
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            CountryCode = "LS",
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            CountryCode = "LR",
                            CountryName = "Liberia"
                        },
                        new
                        {
                            CountryCode = "LY",
                            CountryName = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            CountryCode = "LI",
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            CountryCode = "LT",
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            CountryCode = "LU",
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            CountryCode = "MO",
                            CountryName = "Macao"
                        },
                        new
                        {
                            CountryCode = "MK",
                            CountryName = "Macedonia, The Former Yugoslav Republic of"
                        },
                        new
                        {
                            CountryCode = "MG",
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            CountryCode = "MW",
                            CountryName = "Malawi"
                        },
                        new
                        {
                            CountryCode = "MY",
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            CountryCode = "MV",
                            CountryName = "Maldives"
                        },
                        new
                        {
                            CountryCode = "ML",
                            CountryName = "Mali"
                        },
                        new
                        {
                            CountryCode = "MT",
                            CountryName = "Malta"
                        },
                        new
                        {
                            CountryCode = "MH",
                            CountryName = "Marshall Islands"
                        },
                        new
                        {
                            CountryCode = "MQ",
                            CountryName = "Martinique"
                        },
                        new
                        {
                            CountryCode = "MR",
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            CountryCode = "MU",
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            CountryCode = "YT",
                            CountryName = "Mayotte"
                        },
                        new
                        {
                            CountryCode = "MX",
                            CountryName = "Mexico"
                        },
                        new
                        {
                            CountryCode = "FM",
                            CountryName = "Micronesia, Federated States of"
                        },
                        new
                        {
                            CountryCode = "MD",
                            CountryName = "Moldova, Republic of"
                        },
                        new
                        {
                            CountryCode = "MC",
                            CountryName = "Monaco"
                        },
                        new
                        {
                            CountryCode = "MN",
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            CountryCode = "MS",
                            CountryName = "Montserrat"
                        },
                        new
                        {
                            CountryCode = "MA",
                            CountryName = "Morocco"
                        },
                        new
                        {
                            CountryCode = "MZ",
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            CountryCode = "MM",
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            CountryCode = "NA",
                            CountryName = "Namibia"
                        },
                        new
                        {
                            CountryCode = "NR",
                            CountryName = "Nauru"
                        },
                        new
                        {
                            CountryCode = "NP",
                            CountryName = "Nepal"
                        },
                        new
                        {
                            CountryCode = "NL",
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            CountryCode = "AN",
                            CountryName = "Netherlands Antilles"
                        },
                        new
                        {
                            CountryCode = "NC",
                            CountryName = "New Caledonia"
                        },
                        new
                        {
                            CountryCode = "NZ",
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            CountryCode = "NI",
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            CountryCode = "NE",
                            CountryName = "Niger"
                        },
                        new
                        {
                            CountryCode = "NG",
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            CountryCode = "NU",
                            CountryName = "Niue"
                        },
                        new
                        {
                            CountryCode = "NF",
                            CountryName = "Norfolk Island"
                        },
                        new
                        {
                            CountryCode = "MP",
                            CountryName = "Northern Mariana Islands"
                        },
                        new
                        {
                            CountryCode = "NO",
                            CountryName = "Norway"
                        },
                        new
                        {
                            CountryCode = "OM",
                            CountryName = "Oman"
                        },
                        new
                        {
                            CountryCode = "PK",
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            CountryCode = "PW",
                            CountryName = "Palau"
                        },
                        new
                        {
                            CountryCode = "PS",
                            CountryName = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            CountryCode = "PA",
                            CountryName = "Panama"
                        },
                        new
                        {
                            CountryCode = "PG",
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            CountryCode = "PY",
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            CountryCode = "PE",
                            CountryName = "Peru"
                        },
                        new
                        {
                            CountryCode = "PH",
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryCode = "PN",
                            CountryName = "Pitcairn"
                        },
                        new
                        {
                            CountryCode = "PL",
                            CountryName = "Poland"
                        },
                        new
                        {
                            CountryCode = "PT",
                            CountryName = "Portugal"
                        },
                        new
                        {
                            CountryCode = "PR",
                            CountryName = "Puerto Rico"
                        },
                        new
                        {
                            CountryCode = "QA",
                            CountryName = "Qatar"
                        },
                        new
                        {
                            CountryCode = "RE",
                            CountryName = "Reunion"
                        },
                        new
                        {
                            CountryCode = "RO",
                            CountryName = "Romania"
                        },
                        new
                        {
                            CountryCode = "RU",
                            CountryName = "Russian Federation"
                        },
                        new
                        {
                            CountryCode = "RW",
                            CountryName = "RWANDA"
                        },
                        new
                        {
                            CountryCode = "SH",
                            CountryName = "Saint Helena"
                        },
                        new
                        {
                            CountryCode = "KN",
                            CountryName = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            CountryCode = "LC",
                            CountryName = "Saint Lucia"
                        },
                        new
                        {
                            CountryCode = "PM",
                            CountryName = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            CountryCode = "VC",
                            CountryName = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            CountryCode = "WS",
                            CountryName = "Samoa"
                        },
                        new
                        {
                            CountryCode = "SM",
                            CountryName = "San Marino"
                        },
                        new
                        {
                            CountryCode = "ST",
                            CountryName = "Sao Tome and Principe"
                        },
                        new
                        {
                            CountryCode = "SA",
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            CountryCode = "SN",
                            CountryName = "Senegal"
                        },
                        new
                        {
                            CountryCode = "CS",
                            CountryName = "Serbia and Montenegro"
                        },
                        new
                        {
                            CountryCode = "SC",
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            CountryCode = "SL",
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            CountryCode = "SG",
                            CountryName = "Singapore"
                        },
                        new
                        {
                            CountryCode = "SK",
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            CountryCode = "SI",
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            CountryCode = "SB",
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            CountryCode = "SO",
                            CountryName = "Somalia"
                        },
                        new
                        {
                            CountryCode = "ZA",
                            CountryName = "South Africa"
                        },
                        new
                        {
                            CountryCode = "GS",
                            CountryName = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            CountryCode = "ES",
                            CountryName = "Spain"
                        },
                        new
                        {
                            CountryCode = "LK",
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            CountryCode = "SD",
                            CountryName = "Sudan"
                        },
                        new
                        {
                            CountryCode = "SR",
                            CountryName = "SuriCountryName"
                        },
                        new
                        {
                            CountryCode = "SJ",
                            CountryName = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            CountryCode = "SZ",
                            CountryName = "Swaziland"
                        },
                        new
                        {
                            CountryCode = "SE",
                            CountryName = "Sweden"
                        },
                        new
                        {
                            CountryCode = "CH",
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            CountryCode = "SY",
                            CountryName = "Syrian Arab Republic"
                        },
                        new
                        {
                            CountryCode = "TW",
                            CountryName = "Taiwan, Province of China"
                        },
                        new
                        {
                            CountryCode = "TJ",
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            CountryCode = "TZ",
                            CountryName = "Tanzania, United Republic of"
                        },
                        new
                        {
                            CountryCode = "TH",
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryCode = "TL",
                            CountryName = "Timor-Leste"
                        },
                        new
                        {
                            CountryCode = "TG",
                            CountryName = "Togo"
                        },
                        new
                        {
                            CountryCode = "TK",
                            CountryName = "Tokelau"
                        },
                        new
                        {
                            CountryCode = "TO",
                            CountryName = "Tonga"
                        },
                        new
                        {
                            CountryCode = "TT",
                            CountryName = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryCode = "TN",
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            CountryCode = "TR",
                            CountryName = "Turkey"
                        },
                        new
                        {
                            CountryCode = "TM",
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            CountryCode = "TC",
                            CountryName = "Turks and Caicos Islands"
                        },
                        new
                        {
                            CountryCode = "TV",
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            CountryCode = "UG",
                            CountryName = "Uganda"
                        },
                        new
                        {
                            CountryCode = "UA",
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            CountryCode = "AE",
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            CountryCode = "GB",
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            CountryCode = "US",
                            CountryName = "United States"
                        },
                        new
                        {
                            CountryCode = "UM",
                            CountryName = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            CountryCode = "UY",
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            CountryCode = "UZ",
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            CountryCode = "VU",
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            CountryCode = "VE",
                            CountryName = "Venezuela"
                        },
                        new
                        {
                            CountryCode = "VN",
                            CountryName = "Viet Nam"
                        },
                        new
                        {
                            CountryCode = "VG",
                            CountryName = "Virgin Islands, British"
                        },
                        new
                        {
                            CountryCode = "VI",
                            CountryName = "Virgin Islands, U.S."
                        },
                        new
                        {
                            CountryCode = "WF",
                            CountryName = "Wallis and Futuna"
                        },
                        new
                        {
                            CountryCode = "EH",
                            CountryName = "Western Sahara"
                        },
                        new
                        {
                            CountryCode = "YE",
                            CountryName = "Yemen"
                        },
                        new
                        {
                            CountryCode = "ZM",
                            CountryName = "Zambia"
                        },
                        new
                        {
                            CountryCode = "ZW",
                            CountryName = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("BusinessObject.Film", b =>
                {
                    b.Property<long>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("FilmId"), 1L, 1);

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("DateRelease")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FilmDuration")
                        .HasColumnType("bigint");

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("GenreId");

                    b.ToTable("Film");
                });

            modelBuilder.Entity("BusinessObject.Genre", b =>
                {
                    b.Property<long>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("GenreId"), 1L, 1);

                    b.Property<string>("GenreName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genre");
                });

            modelBuilder.Entity("BusinessObject.RechargeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPay")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RechargeRequest");
                });

            modelBuilder.Entity("BusinessObject.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenRefresh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("BusinessObject.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"), 1L, 1);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1L,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2L,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("BusinessObject.Room", b =>
                {
                    b.Property<long>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoomId"), 1L, 1);

                    b.Property<int>("NumberColumn")
                        .HasColumnType("int");

                    b.Property<int>("NumberRow")
                        .HasColumnType("int");

                    b.Property<string>("RoomName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("BusinessObject.Show", b =>
                {
                    b.Property<long>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShowId"), 1L, 1);

                    b.Property<long>("FilmId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint");

                    b.Property<string>("SeatStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShowDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ShowId");

                    b.HasIndex("FilmId");

                    b.HasIndex("RoomId");

                    b.ToTable("Show");
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1);

                    b.Property<long>("AccountBalance")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConfirmEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLoginGoogle")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BusinessObject.Booking", b =>
                {
                    b.HasOne("BusinessObject.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Show");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Film", b =>
                {
                    b.HasOne("BusinessObject.Country", "Country")
                        .WithMany("Films")
                        .HasForeignKey("CountryCode");

                    b.HasOne("BusinessObject.Genre", "Genre")
                        .WithMany("Films")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BusinessObject.RechargeRequest", b =>
                {
                    b.HasOne("BusinessObject.User", "User")
                        .WithMany("RechargeRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.RefreshToken", b =>
                {
                    b.HasOne("BusinessObject.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.Show", b =>
                {
                    b.HasOne("BusinessObject.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Room", "Room")
                        .WithMany("Shows")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.HasOne("BusinessObject.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObject.Country", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("BusinessObject.Genre", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("BusinessObject.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessObject.Room", b =>
                {
                    b.Navigation("Shows");
                });

            modelBuilder.Entity("BusinessObject.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RechargeRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
